# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      # Runs the build script
      - name: Run the build script
        run: ./build_web.sh
        
      # commit the game files to github pages branch
      - name: Commit the game files to the github pages branch
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          BRANCH: gh-pages
          FOLDER: web_build
      
